name: TeamChatPrefix
version: 1.0
main: de.beqare.teamchatprefix.TeamChatPrefix
api-version: 1.21
author: beqare
description: Change the Chat Format to the Vanilla Team Prefix / Color
website: https://jonasgrimm.de
