name: TeamChatPrefix
version: 1.1
main: de.beqare.teamChatPrefix.TeamChatPrefix
api-version: 1.21
author: beqare
description: Plugin to use Team Prefix/Color for chat format!
website: https://github.com/beqare/TeamChatPrefix